name: Create review app

on:
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: ${{ secrets.KNOWN_HOSTS }}
      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
      - name: Copy files to the server
        run: |
          rsync -a -r --progress --human-readable --delete \
          --exclude-from '.gitignore' \
          . $SSH_USERNAME@$SSH_HOST:~/var/www/testing/${{ github.head_ref }}/
        env:
         SSH_USER: ${{ secrets.SSH_USERNAME }}
         SSH_HOST: ${{ secrets.SSH_HOST }}
      - name: Init the app
        run: |
          ssh $SSH_USERNAME@$SSH_HOST "pushd ~/var/www/testing/${{ github.head_ref }} && ./bin/start && popd"
        env:
         SSH_USER: ${{ secrets.SSH_USERNAME }}
         SSH_HOST: ${{ secrets.SSH_HOST }}
